version: 2
name: MyDAGPipeline
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: Build
            template: build-template
          - name: Deploy
            template: deploy-template
            dependencies:
              - Build
          - name: Notify
            template: notify-template
            dependencies:
              - Deploy
  templates:
    - name: build-template
      container:
        image: "ubuntu:22.04"
        commands:
          - echo "Installing dependencies..."
          - apt-get update
          - apt-get install -y nodejs npm
          - echo "Running tests..."
          - npm test

    - name: deploy-template
      container:
        image: "ubuntu:22.04"
        commands:
          - echo "Deploying to production..."
          - npm run deploy

    - name: notify-template
      container:
        image: "ubuntu:22.04"
        commands:
          - echo "Sending notifications..."
          - apt-get install -y curl
          - curl -X POST -d '{"text":"Deployment completed successfully!"}' https://example.com/notify
