version: v2
global:
  runner:
    os_image: ubuntu
  variables:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    - GOFLAGS=-mod=vendor
    - LD_FLAGS=-w -s

tasks:
  add-binary:
    steps:
    - checkout
      commands:
      - chmod +x *  # Make your binary executable (adjust path)
      - ls -l ./bgmi      # Verify permissions for debugging (optional)

  run-python-script:
    depends: [add-binary]  # Ensure this runs after the binary permissions are set
    steps:
    - checkout
      run: |
        python3 -m pip install --upgrade pip
        pip install python-telegram-bot flask
      commands:
      - python3 evil.py  # Run the Python script (adjust path)
